server:
  port: 9000
  
spring:
  application:
    name: mail-service
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

# H2 configuration
  datasource:
    generate-unique-name: false
  sql:
    init:
      mode: embedded

# MySQL configuration
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.99.100:3306/mailer?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root